#carta al futuro
print("+----------------------------------------------------------+")
print("|                                                15/09/2022|")
print("|                                                          |")
print("| Futuro Tute:                                             |")
print("|                                                          |")
print("| Hoy me siento bien😄😄                                  |")
print("| Espero poder conseguir un trabajo y dedicarme a esto     |")
print("| En 3 meses voy a estar pudiendo programar correctamente  |")
print("| Dedicate como tiene que ser, al 100%                     |")
print("| 🎮🇦🇷                                                     |")
print("|                                                          |")
print("| Saludos!                                                 |")
print("|                                                          |")
print("|                                                  Atte: YO|")
print("+----------------------------------------------------------+")
